id: P007108
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25144
  title: ལམ་རིམ་བདུད་རྩི་སྙིང་པོ།
  author: ''
  volumes:
    0738882b34a240d6846319e25cf438cd:
      image_group_id: I1KG25146
      title: ''
      volume_number: 1
      total_pages: 150
ebook_metadata:
  title: ལམ་རིམ་བདུད་རྩི་སྙིང་པོ།
  author: ''
  sku: P007108
  cover: cover.jpg
  layers:
  - pagination
